---
- hosts: all
  gather_facts: true
  become: true
  tasks:
    - yum:
        name: telnet
      when: ansible_os_family == "RedHat"
    - apt:
        name: telnet
      when: ansible_os_family == "Debian"
