---
- hosts: redis1
  become: yes
  tasks:
    - name: Install single node Redis
      vars:
        redis_version: 5.0.10
        redis_port: 6379
        redis_bind: 192.168.70.11
        redis_socket: /var/run/redis/redis.sock
        redis_password: redispwd
      include_role: 
        name: davidwittman.redis
