- name: configure redis sentinel nodes
  hosts: redis-sentinel
  vars:
    - redis_sentinel_monitors:
      - name: redis1
        host: 192.168.70.11
        port: 6379
  roles:
    - DavidWittman.redis